name: Terraform Deploy + Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
    #   AWS_REGION: ap-south-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
  
    - name: Terraform fmt
      run: terraform fmt
   
    - name: Terraform validate
      run: terraform validate
   
    - name: Terraform plan
      run: terraform plan --var-file zones.tfvars
    
    # - name: Terraform Apply
    #   run: terraform apply --var-file zones.tfvars -auto-approve
   
    # - name: Terraform destroy
    #   run: terraform destroy --var-file zones.tfvars --auto-approve
   
